import type { Impact, ResolvedStandard, WcagLevel } from '@accessible-ai/standards';
import type { AccessibilityIssue, AutomationLevel, EstimatedEffort } from '../../config/types.js';
import { getGroupSize } from './deduplicator.js';
import type { FixItem, FixPhase, FixPlan, FixType, PlanConfig, PrioritizeBy } from './types.js';

// Reuses the same {A:3, AA:2, AAA:1} weighting `static-analyzer/analyzer.ts`'s `calculateStaticComplianceScore`
// and the extension's score calculator already use, so "legal risk" and compliance-score talk stay consistent.
const LEVEL_WEIGHT: Record<WcagLevel, number> = { A: 3, AA: 2, AAA: 1 };
const IMPACT_SCORE: Record<Impact, number> = { critical: 40, serious: 30, moderate: 20, minor: 10 };
const EFFORT_SCORE: Record<EstimatedEffort, number> = { trivial: 40, small: 30, medium: 20, large: 10 };
const EFFORT_DAYS: Record<EstimatedEffort, number> = { trivial: 0.125, small: 0.375, medium: 1, large: 2.5 };

/**
 * Weight profiles for `calculatePriority`'s four terms (impact / legal risk / inverse-effort / blast
 * radius). Not defined anywhere in the architecture doc — designed here from scratch, biasing each
 * profile toward the term its name promises while keeping the other three as meaningful tie-breakers.
 */
const PRIORITY_WEIGHTS: Record<PrioritizeBy, { impact: number; legal: number; effort: number; reach: number }> = {
  impact: { impact: 1.0, legal: 0.3, effort: 0.3, reach: 0.4 },
  effort: { impact: 0.4, legal: 0.2, effort: 1.0, reach: 0.4 },
  'wcag-level': { impact: 0.5, legal: 0.3, effort: 0.2, reach: 0.3 },
  'legal-risk': { impact: 0.3, legal: 1.0, effort: 0.2, reach: 0.3 },
};

const PHASE_DEFS: Record<AutomationLevel, { phase: number; name: string; description: string; fixType: FixType }> = {
  auto: {
    phase: 1,
    name: 'Quick Wins — Automated Fixes',
    description: 'Deterministic template-based fixes (e.g. missing lang attribute, duplicate ids, positive tabindex) that need no review before applying.',
    fixType: 'auto-template',
  },
  'llm-assisted': {
    phase: 2,
    name: 'AI-Assisted Fixes',
    description: 'Fixes that need real content or context (alt text, labels, accessible names) — generated by Claude, reviewed before merging.',
    fixType: 'llm-generated',
  },
  'manual-review': {
    phase: 3,
    name: 'Manual Review',
    description: 'Judgment calls (heading restructuring, color contrast, ARIA pattern design) that automation shouldn’t attempt.',
    fixType: 'manual-guidance',
  },
};

function calculateLegalRisk(issue: AccessibilityIssue, resolved: ResolvedStandard): number {
  const levels = issue.wcagCriteria
    .map((id) => resolved.criteria.find((c) => c.id === id)?.level)
    .filter((level): level is WcagLevel => Boolean(level));
  const levelScore = levels.length > 0 ? Math.max(...levels.map((level) => LEVEL_WEIGHT[level])) * 10 : 10;
  return levelScore + IMPACT_SCORE[issue.impact] * 0.25;
}

function calculatePriority(issue: AccessibilityIssue, config: PlanConfig, resolved: ResolvedStandard, allIssues: AccessibilityIssue[]): number {
  const weights = PRIORITY_WEIGHTS[config.prioritizeBy];
  const impactScore = IMPACT_SCORE[issue.impact];
  const legalScore = calculateLegalRisk(issue, resolved);
  const effortScore = EFFORT_SCORE[issue.remediation.estimatedEffort];
  const blastRadius = (issue.remediation.groupId ? getGroupSize(issue.remediation.groupId, allIssues) : 1) * 5;

  return impactScore * weights.impact + legalScore * weights.legal + effortScore * weights.effort + blastRadius * weights.reach;
}

function formatEffort(days: number): string {
  if (days <= 0) return '0 developer days';
  const low = Math.max(0.1, Math.round(days * 0.75 * 10) / 10);
  const high = Math.round(days * 1.25 * 10) / 10;
  return `${low}-${high} developer days`;
}

/**
 * Builds the 3-phase remediation plan (architecture doc section 5.3). Issues sharing a
 * `remediation.groupId` (same rule — see `deduplicator.ts`'s `getGroupSize`) collapse into one
 * `FixItem` per phase, with the rest listed in `fix.resolvesIssueIds`. `projectedScoreAfter` per phase
 * is a proportional approximation (fraction of issues resolved so far, interpolated toward 100%) — a
 * true per-criterion recompute would need the full pass/fail criterion set issues alone don't carry.
 */
export function generateFixPlan(
  issues: AccessibilityIssue[],
  resolved: ResolvedStandard,
  complianceScoreBefore: number,
  config: PlanConfig,
): FixPlan {
  const scored = issues.map((issue) => ({ issue, priority: calculatePriority(issue, config, resolved, issues) }));
  scored.sort((a, b) => b.priority - a.priority);

  const byLevel: Record<AutomationLevel, typeof scored> = { auto: [], 'llm-assisted': [], 'manual-review': [] };
  for (const entry of scored) byLevel[entry.issue.remediation.automationLevel].push(entry);

  let resolvedSoFar = 0;
  const totalIssues = issues.length;
  const phases: FixPhase[] = [];

  for (const level of ['auto', 'llm-assisted', 'manual-review'] as const) {
    const group = byLevel[level];
    if (group.length === 0) continue;

    const def = PHASE_DEFS[level];
    const seenGroups = new Set<string>();
    const fixItems: FixItem[] = [];

    for (const { issue, priority } of group) {
      const groupId = issue.remediation.groupId;
      if (groupId && seenGroups.has(groupId)) continue;
      if (groupId) seenGroups.add(groupId);

      const groupMembers = groupId ? group.filter((entry) => entry.issue.remediation.groupId === groupId) : [{ issue, priority }];
      fixItems.push({
        issueId: issue.id,
        priority,
        issue,
        fix: {
          type: def.fixType,
          resolvesCriteria: Array.from(new Set(groupMembers.flatMap((entry) => entry.issue.wcagCriteria))),
          resolvesIssueIds: groupMembers.map((entry) => entry.issue.id),
        },
        verification: { rerunRules: [issue.ruleId] },
      });
    }

    resolvedSoFar += fixItems.reduce((sum, item) => sum + item.fix.resolvesIssueIds.length, 0);
    const projectedScoreAfter = complianceScoreBefore + (resolvedSoFar / totalIssues) * (100 - complianceScoreBefore);
    const totalDays = fixItems.reduce((sum, item) => sum + EFFORT_DAYS[item.issue.remediation.estimatedEffort], 0);

    phases.push({
      phase: def.phase,
      name: def.name,
      description: `${def.description} Projected compliance after this phase: ${Math.round(projectedScoreAfter)}%.`,
      estimatedEffort: formatEffort(totalDays),
      issues: fixItems,
    });
  }

  if (config.maxItems) {
    let remaining = config.maxItems;
    for (const phase of phases) {
      phase.issues = remaining > 0 ? phase.issues.slice(0, remaining) : [];
      remaining -= phase.issues.length;
    }
  }

  const totalDaysAll = issues.reduce((sum, issue) => sum + EFFORT_DAYS[issue.remediation.estimatedEffort], 0);
  const projectedScoreAfterAll = totalIssues > 0 ? 100 : complianceScoreBefore;

  return {
    id: `plan-${Date.now()}`,
    standard: resolved.standard.id,
    generatedAt: new Date().toISOString(),
    summary: {
      totalIssues,
      autoFixable: byLevel.auto.length,
      llmAssisted: byLevel['llm-assisted'].length,
      manualReview: byLevel['manual-review'].length,
      estimatedTotalEffort: formatEffort(totalDaysAll),
      complianceScoreBefore,
      projectedScoreAfter: Math.round(projectedScoreAfterAll),
    },
    phases,
  };
}
